services:
  - type: web
    name: resume-builder
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: MISTRAL_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1
